version: "3.9"  # optional since v1.27.0
services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./src:/app
      - ./db:/db
  nginx:
    ports: 
      - "8888:80"
    volumes:
      - ./src:/app
      - ./db:/db
    build:
      context: .
      dockerfile: nginx/Dockerfile